#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_MINS, KC_EQL, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NUHS, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LCTL, LGUI_T(KC_Z), LALT_T(KC_X), LCTL_T(KC_C), LSFT_T(KC_V), KC_B, KC_DEL, KC_NO, KC_N, RSFT_T(KC_M), RCTL_T(KC_COMM), RALT_T(KC_DOT), RGUI_T(KC_SLSH), KC_DEL, QK_TRI_LAYER_LOWER, QK_TRI_LAYER_LOWER, KC_BSPC, KC_SPC, KC_ENT, QK_TRI_LAYER_UPPER),
    [1] = LAYOUT(KC_NO, KC_GRV, KC_TILD, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_EXLM, KC_CIRC, KC_ASTR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCBR, KC_RCBR, KC_AT, KC_HASH, KC_UP, KC_DLR, KC_PERC, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_GRV, KC_LEFT, KC_DOWN, KC_RGHT, KC_AMPR, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_HOME, KC_END, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [2] = LAYOUT(KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_PMNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO, KC_VOLU, KC_TRNS, KC_NO, KC_P1, KC_P2, KC_P3, KC_COMM, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_MPLY, KC_VOLD, KC_TRNS, KC_PAST, KC_PSLS, KC_P0, KC_PDOT, KC_PEQL, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_MPRV, KC_MUTE, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [3] = LAYOUT(QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_SLEP, RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_MOD, RGB_SPI, RGB_VAI, RGB_SAI, RGB_HUI, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, RGB_RMOD, RGB_SPD, RGB_VAD, RGB_SAD, RGB_HUD, KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_NO, RSFT(KC_NO), RCTL(KC_NO), RALT(KC_NO), RGUI(KC_NO), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



// Pasted from `./keymapAchordion.c`
// Code from here: https://getreuer.info/posts/keyboards/achordion/index.html#add-achordion-to-your-keymap

#include "features/achordion.h"

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
  if (!process_achordion(keycode, record)) { return false; }
  // Your macros ...

  return true;
}

void matrix_scan_user(void) {
  achordion_task();
}
